// ─── Core Concepts — ELI5 Explanations ───────────────────────────────────────
// Every concept has a technical explanation and a plain-English analogy.

export interface Concept {
  id: string;
  title: string;
  icon: string;
  shortSummary: string;              // One-liner for the glossary list
  explanation: string;               // Technical explanation
  plainEnglish: string;              // "Explain like I'm 5" version
  relatedFlows: string[];            // IDs of demo flows that use this concept
  relatedArchNodes: string[];        // Titles of architecture nodes that map here
  examples?: string[];               // Real-world analogies or examples
}

export const concepts: Concept[] = [
  {
    id: "vector_database",
    title: "Vector Database",
    icon: "🗄️",
    shortSummary: "A smart filing cabinet that finds things by meaning, not by name",
    explanation:
      "A vector database stores data as high-dimensional numerical vectors (embeddings). Instead of searching by exact keyword match, it finds items that are semantically similar using mathematical distance metrics like cosine similarity. Think of it as a map where similar ideas are placed close together — 'payment processing' and 'credit card checkout' end up as neighbors even though the words are completely different.",
    plainEnglish:
      "Imagine a magical filing cabinet. You don't need to know the exact label on a folder — you just describe what you're looking for in plain English, and the cabinet finds the most relevant folders. That's what a vector database does: it understands the *meaning* of what you're asking for, not just the exact words.",
    relatedFlows: ["rag", "indexing", "bridge"],
    relatedArchNodes: ["Vector Store", "Embedding Engine"],
    examples: [
      "Google Images: you type 'happy dog', and it finds photos of dogs that look happy — even if no photo has those exact words in its filename.",
      "Spotify's 'Discover Weekly': songs you've never heard but *feel* similar to what you like — that's vector similarity in action.",
    ],
  },
  {
    id: "embedding",
    title: "Embedding (Text → Numbers)",
    icon: "🔢",
    shortSummary: "Converting words into a secret language the computer understands",
    explanation:
      "An embedding is a dense vector representation of text generated by a neural network (like text-embedding-3-small). Each word, sentence, or document becomes a point in a 1536-dimensional space where semantic similarity maps to geometric proximity. The model is trained so that sentences with similar meanings produce vectors that are close together when measured by cosine similarity. All vectors are L2-normalized so comparisons use simple dot products.",
    plainEnglish:
      "Imagine every word has a secret coordinate, like a GPS location for meaning. 'Cat' might be at (0.2, 0.8, ...) and 'kitten' would be very nearby, but 'tax return' would be far away. An embedding model is the GPS — it converts words into these coordinates so the computer can understand which things are similar. Two sentences that mean the same thing end up at nearly the same spot.",
    relatedFlows: ["rag", "indexing"],
    relatedArchNodes: ["Embedding Engine"],
    examples: [
      "'I love dogs' and 'Puppies are amazing' land close together in vector space.",
      "'I love dogs' and 'Tax filing deadlines' land far apart.",
    ],
  },
  {
    id: "rag",
    title: "RAG (Retrieval-Augmented Generation)",
    icon: "🤖",
    shortSummary: "Look up facts first, then answer — like an open-book exam",
    explanation:
      "RAG is a pattern where an LLM answers questions by first retrieving relevant documents from a knowledge base, then generating a response grounded in those documents. The pipeline: (1) embed the user's question, (2) search the vector store for similar chunks, (3) assemble retrieved chunks into the LLM's context prompt with source attribution, (4) the LLM generates an answer based on that context. This dramatically reduces hallucinations because the model is constrained to answer from real documents.",
    plainEnglish:
      "Imagine you're taking an exam but you're allowed to look at your notes. RAG is exactly that: the AI 'looks up' relevant information in your codebase before answering. So when you ask 'How does login work?', it first finds the login-related code, reads it, and then explains it to you based on what it actually found — not making things up.",
    relatedFlows: ["rag"],
    relatedArchNodes: ["RAG Pipeline", "User Query"],
    examples: [
      "Asking 'What's our refund policy?' → RAG finds the refund doc → answers accurately.",
      "Without RAG: the AI guesses. With RAG: the AI reads your actual documents first.",
    ],
  },
  {
    id: "chunking",
    title: "Chunking",
    icon: "✂️",
    shortSummary: "Breaking big documents into bite-sized pieces for better search",
    explanation:
      "Chunking splits large documents into smaller, overlapping segments (typically ~512 tokens with 50-token overlap). This is critical because: (1) LLMs have context window limits, (2) smaller chunks produce more precise search results, and (3) overlap ensures no context is lost at chunk boundaries. Mimir uses LlamaIndex's recursive chunking strategy that's aware of document structure.",
    plainEnglish:
      "Imagine cutting a 500-page textbook into individual paragraphs, but with a little overlap between each cut so you don't lose important context at the edges. Each paragraph becomes its own searchable piece. When you ask a question, the system only needs to find the right paragraph(s) instead of reading the entire book.",
    relatedFlows: ["indexing"],
    relatedArchNodes: ["Embedding Engine"],
    examples: [
      "A 10,000-line source file gets split into ~20 chunks, each independently searchable.",
      "50-token overlap means a function that spans two chunks still has full context.",
    ],
  },
  {
    id: "cosine_similarity",
    title: "Cosine Similarity",
    icon: "📐",
    shortSummary: "Measuring how close two ideas are by the angle between their arrows",
    explanation:
      "Cosine similarity measures the cosine of the angle between two vectors in high-dimensional space. It ranges from -1 (opposite) to 1 (identical direction), with values near 1 indicating high semantic similarity. Unlike Euclidean distance, cosine similarity is unaffected by vector magnitude — it only cares about direction. Mimir uses this to rank document chunks against queries, returning the top-k most similar results.",
    plainEnglish:
      "Picture two arrows pointing from the same spot. If they point in the same direction (small angle), they're very similar (cosine ≈ 1). If they're perpendicular, they're unrelated (cosine ≈ 0). If they point opposite ways, they're dissimilar (cosine ≈ -1). Mimir uses this math trick to figure out which documents are most like your question.",
    relatedFlows: ["rag"],
    relatedArchNodes: ["Vector Store"],
    examples: [
      "Query: 'How to authenticate' matches 'Login middleware implementation' (cosine ≈ 0.89).",
      "Query: 'How to authenticate' does NOT match 'CSS styling guide' (cosine ≈ 0.12).",
    ],
  },
  {
    id: "manifest",
    title: "Index Manifest",
    icon: "📋",
    shortSummary: "A ledger that tracks what's been indexed and when",
    explanation:
      "The manifest.json is Mimir's source of truth about the index state. It records: which files have been indexed, their SHA-256 hashes, document counts, directory mappings, and the last update timestamp. On each indexing run, Mimir compares current file hashes against the manifest — if unchanged, the file is skipped entirely. This enables O(changed) incremental updates instead of O(n) full rebuilds.",
    plainEnglish:
      "Imagine a librarian who keeps a notebook of every book they've put on the shelf, with a fingerprint (hash) for each book. When new books arrive, they only check the ones NOT already in the notebook. The manifest is that notebook — it remembers everything so you don't have to redo work.",
    relatedFlows: ["indexing"],
    relatedArchNodes: ["Manifest DB", "File Watcher"],
    examples: [
      "Git checkout changes a file's timestamp — but the hash is the same, so Mimir skips it.",
      "Manifest version 1.0 format with per-directory file listings.",
    ],
  },
  {
    id: "circuit_breaker",
    title: "Circuit Breaker",
    icon: "⚡",
    shortSummary: "A safety switch that stops hammering a broken service",
    explanation:
      "The circuit breaker pattern prevents cascading failures when an external service (like OpenAI or an API) is down. After N consecutive failures (default 3), the circuit 'opens' and all subsequent calls are blocked for a cooldown period (default 60s). After cooldown, it transitions to 'half-open' and allows one test request. If that succeeds, the circuit closes again. States: CLOSED → OPEN → HALF_OPEN → CLOSED.",
    plainEnglish:
      "Imagine your doorbell has a circuit breaker. If you press it 3 times and nobody answers, it stops ringing for a minute to give the person a break. After a minute, it tries once more. If someone answers, great — back to normal. If not, it waits again. This prevents annoying everyone while also not giving up permanently.",
    relatedFlows: ["bridge"],
    relatedArchNodes: ["MCP Server"],
    examples: [
      "OpenAI API goes down → 3 failed calls → circuit opens → no more calls for 60s.",
      "Prevents thread exhaustion and cascading failures across your system.",
    ],
  },
  {
    id: "lru_cache",
    title: "LRU Cache",
    icon: "💨",
    shortSummary: "Remembering recent answers so you don't ask twice",
    explanation:
      "An LRU (Least Recently Used) cache stores the most recently accessed items up to a max size (default 128). When the cache is full and a new item needs to be added, the least recently used item is evicted. Mimir uses TTL-based caching (default 600 seconds) so cached results expire and get refreshed. Each cache key is a SHA-256 hash of the query + parameters.",
    plainEnglish:
      "Imagine you have a tiny desk that can only hold 5 books. You keep the ones you use most recently, and when the desk is full, you push out the book you haven't touched in the longest time. Also, if a book has been sitting there for 10 minutes, you toss it out and grab a fresh copy. That's an LRU cache with TTL.",
    relatedFlows: ["bridge"],
    relatedArchNodes: ["MCP Server"],
    examples: [
      "Ask the same question twice within 10 minutes → instant answer from cache.",
      "Ask 129 different questions → the first one gets evicted from the 128-slot cache.",
    ],
  },
  {
    id: "content_filter",
    title: "Content Filter",
    icon: "🛡️",
    shortSummary: "A security guard that keeps secrets from leaking out",
    explanation:
      "The content filter scans every retrieved document chunk before it reaches the LLM. It checks for: (1) sensitive patterns like API keys, passwords, private IPs, using regex; (2) blocked filenames like .env, credentials.json, *secret*. Matching content is redacted with [REDACTED] and blocked files are excluded entirely. This is the last line of defense against data leakage.",
    plainEnglish:
      "Before anything goes to the AI, a security guard checks it. If the guard sees passwords, API keys, or your .env file, they redact it (replace it with ****) or throw it away entirely. Think of it like a bouncer at a club — if you're carrying something dangerous, you don't get in.",
    relatedFlows: ["bridge"],
    relatedArchNodes: ["Content Filter"],
    examples: [
      "A source file contains 'API_KEY=sk-abc123' → the AI sees 'API_KEY=[REDACTED]'.",
      "The file '.env.production' is filtered out completely and never reaches the LLM.",
    ],
  },
  {
    id: "sha256_hashing",
    title: "SHA-256 Hashing",
    icon: "🔐",
    shortSummary: "Creating a unique fingerprint for every file",
    explanation:
      "SHA-256 is a cryptographic hash function that takes any input and produces a fixed 256-bit (64 hex characters) output. The same input always produces the same hash, but even a tiny change in input produces a completely different hash. Mimir uses SHA-256 to detect file changes — if a file's hash matches what's in the manifest, it hasn't changed and can be skipped.",
    plainEnglish:
      "Imagine every file has a unique fingerprint. If you change even one comma in a 10,000-line file, the fingerprint changes completely. Mimir compares fingerprints instead of reading every file — same fingerprint means 'nothing changed, skip it!'",
    relatedFlows: ["indexing"],
    relatedArchNodes: ["File Watcher"],
    examples: [
      "Adding a semicolon to config.py → completely different hash → Mimir re-reads that file only.",
      "Git checkout preserves content hash → Mimir correctly skips the file.",
    ],
  },
  {
    id: "knowledge_graph",
    title: "Knowledge Graph",
    icon: "🕸️",
    shortSummary: "A map of how your code connects to itself",
    explanation:
      "The knowledge graph extracts structured relationships from source code using Python's AST module and tree-sitter parsers. It identifies imports, inheritance, method calls, and class definitions across languages (Python, TypeScript, JavaScript, Rust, Go). This creates a graph of nodes (classes, functions, files) and edges (imports, calls, inherits), enabling structural queries like 'what calls this function?' or 'what does this module depend on?'",
    plainEnglish:
      "Imagine drawing a map of your entire codebase. Every file is a city, every import is a road, every function call is a delivery route. The knowledge graph builds this map automatically so when you ask 'how does data flow from login to the database?', you can trace the path on the map instead of reading every file.",
    relatedFlows: ["agent"],
    relatedArchNodes: ["MCP Server", "LangGraph Router"],
    examples: [
      "graph_neighbors('openspace_bridge.py', depth=2) → finds 8 connected modules.",
      "Answers 'What depends on this module?' without reading every file in the project.",
    ],
  },
  {
    id: "langgraph",
    title: "LangGraph (Orchestration)",
    icon: "🔀",
    shortSummary: "The air traffic controller that decides which workflow to run",
    explanation:
      "LangGraph is a framework for building stateful, multi-step agent workflows. Mimir uses it as an orchestration layer that routes queries to the appropriate workflow (simple search, full RAG, or multi-turn agent). The knowledge agent uses LangGraph's graph-based state machine to iteratively decide: which tool to call → call it → observe results → decide if more information is needed → loop until confident.",
    plainEnglish:
      "Think of LangGraph as a smart switchboard operator. When you ask a question, it figures out: 'This is simple — just search.' or 'This is complex — I need to explore multiple things, check results, and try again.' It manages the whole conversation loop so the AI doesn't get lost or give up too early.",
    relatedFlows: ["agent"],
    relatedArchNodes: ["LangGraph Router", "Knowledge Agent"],
    examples: [
      "Simple question → 1 search → answer. Complex question → 5 tool calls → 3 loops → comprehensive answer.",
      "The agent decides to call graph_neighbors, sees 8 results, then decides to read specific files.",
    ],
  },
  {
    id: "incremental_indexing",
    title: "Incremental Indexing",
    icon: "🔄",
    shortSummary: "Only updating what changed instead of rebuilding everything",
    explanation:
      "Mimir's file watcher uses SHA-256 hash comparison (not file timestamps) to detect changes. On each run, it computes hashes for all watched files, compares against the hash state in .mimir/index_state.json, and only re-indexes files whose content actually changed. This makes updates O(changed_files) instead of O(all_files), which is critical for large codebases where full rebuilds would be prohibitively slow and expensive.",
    plainEnglish:
      "Instead of re-reading your entire library every time one page changes, Mimir only re-reads the pages that actually changed. It knows which pages changed by checking each page's fingerprint. If the fingerprint is the same, it skips that page entirely.",
    relatedFlows: ["indexing"],
    relatedArchNodes: ["File Watcher", "Manifest DB"],
    examples: [
      "1000 files in a project, 3 changed → only re-index those 3 (0.3% of the work).",
      "timestamps lie (git checkout changes mtime) but fingerprints don't.",
    ],
  },
  {
    id: "mcp_protocol",
    title: "MCP (Model Context Protocol)",
    icon: "🔌",
    shortSummary: "A universal connector so any AI tool can use Mimir",
    explanation:
      "MCP is an open protocol that lets AI clients (Claude, OpenCode, Cursor, etc.) connect to external tools and data sources. Mimir exposes its capabilities — graph traversal, semantic search, file reading — as MCP tools. Any MCP-compatible client can call these tools without writing custom integrations. The bridge pattern keeps Mimir's internal logic separate from the client interface.",
    plainEnglish:
      "MCP is like a USB port for your AI. Just as USB lets any mouse work with any computer, MCP lets any AI tool (Claude, Cursor, etc.) use Mimir's brain without needing special wiring. Mimir just says 'here's what I can do' and the AI says 'I'd like that, please.'",
    relatedFlows: ["agent", "bridge"],
    relatedArchNodes: ["MCP Client", "MCP Server"],
    examples: [
      "Claude Desktop calls Mimir's graph_neighbors tool via MCP.",
      "Cursor can search your codebase using Mimir without any custom plugin.",
    ],
  },
  {
    id: "shared_index",
    title: "Shared Indexes",
    icon: "🌐",
    shortSummary: "Using one team's index in another project's queries",
    explanation:
      "SharedIndexRegistry allows multiple projects to query pre-built indexes from a central location (~/.mimir/shared-indexes/). Each shared index is validated for embedding model compatibility before use. Results from shared and local indices are merged and ranked by score using TaggedNode attribution. This lets a team index a large SDK once and have every project reference it.",
    plainEnglish:
      "Imagine your whole team builds a shared encyclopedia of your company's SDKs. Any project can tap into that encyclopedia when answering questions, in addition to its own notes. Shared indexes are like borrowing someone else's well-organized notes — but you verify they use the same language/dialect (embedding model) first.",
    relatedFlows: [],
    relatedArchNodes: ["LangGraph Router"],
    examples: [
      "Index your internal SDK once → every microservice project can query it.",
      "Team A indexes React docs → Team B's project can search React docs alongside their own code.",
    ],
  },
];

export const conceptQuickIndex: Record<string, string[]> = {
  "indexing": ["vector_database", "embedding", "chunking", "sha256_hashing", "incremental_indexing", "manifest"],
  "rag": ["vector_database", "embedding", "rag", "cosine_similarity", "chunking"],
  "agent": ["knowledge_graph", "langgraph", "mcp_protocol", "cosine_similarity"],
  "bridge": ["circuit_breaker", "lru_cache", "content_filter", "mcp_protocol"],
};